export const PTR_KEY = "__PTR"
export const TBL_KEY = "__TBL"
export const KIND_PRIMITIVE_ARRAY = "primitiveArray"
export const KIND_SUB_ARRAY = "subArray"
export const KIND_PRIMITIVE = "primitive"
export const KIND_ROOT = "root"
export const KIND_MULTI_ARRAY = "multiArray"
export const KIND_SUB = "sub"
export type SchemaRtKinds = typeof KIND_PRIMITIVE | typeof KIND_PRIMITIVE_ARRAY | typeof KIND_SUB_ARRAY | typeof KIND_ROOT | typeof KIND_MULTI_ARRAY | typeof KIND_SUB